---
- name: Configure homelab hosts
  hosts: all
  remote_user: adrian
  become: true
  vars:
    user: adrian
  roles:
    - update
    - update_hosts
    - ssh
    - sudo
    - unattended_upgrades
    - packages
    - docker
