- name: Install apt package
  apt:
    name: "unattended-upgrades"
    state: latest

- name: Enable distro updates/reboot
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    search_string: 'origin=Debian,codename=${distro_codename}-updates'
    line: '"origin=Debian,codename=${distro_codename}-updates:";'

- name: Enable automatic reboot if required
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    search_string: 'Unattended-Upgrade::Automatic-Reboot "false";'
    line: 'Unattended-Upgrade::Automatic-Reboot "true";'

- name: Allow automatic reboot if user is active
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    search_string: 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";'
    line: 'Unattended-Upgrade::Automatic-Reboot-WithUsers "true";'

- name: Set automatic reboot to 2:00 am
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    search_string: 'Unattended-Upgrade::Automatic-Reboot-Time'
    line: 'Unattended-Upgrade::Automatic-Reboot-Time "02:00";'

- name: Log to syslog on automatic updates
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    search_string: 'Unattended-Upgrade::SyslogEnable'
    line: 'Unattended-Upgrade::SyslogEnable "true";'
