---
- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest

- name: Ensure podman is running and enabled
  service:
    name: podman.socket
    state: started
    enabled: true
