---
komodo_periphery_root_directory: /opt
komodo_periphery_project_directory: /opt/komodo
komodo_periphery_stack_directory: /opt/docker/stacks
komodo_periphery_repo_directory: /opt/komodo/repos
komodo_periphery_build_directory: /opt/komodo/builds
komodo_update_production_compose_file: compose.yaml
komodo_update_production_override_file: compose.ansible.yaml
